### ISSUE TITLE
OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by joseddg92** [kigawas/web3-input-decoder#54]
I don't have a way to reproduce it, but here is a stack frame:

```
Traceback (most recent call last):
  File "Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File " pyevm\lib\EVMBlockchain.py", line 109, in __new_blocks_thread_run
    self.__trigger_new_block(new_block)
  File " pyevm\lib\EVMBlockchain.py", line 63, in __trigger_new_block
    decoded_fn_data = decode_function_v2(UNISWAP_V2_ABI, tx.input)
  File " pyevm\lib\decoder.py", line 54, in decode_function_v2
    values = decode_abi(types, args)
  File "C:\global_python_env\lib\site-packages\eth_abi\codec.py", line 181, in decode_abi
    return decoder(stream)
  File "C:\global_python_env\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\global_python_env\lib\site-packages\eth_utils\functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "C:\global_python_env\lib\site-packages\eth_abi\decoding.py", line 173, in decode
    yield decoder(stream)
  File "C:\global_python_env\lib\site-packages\eth_abi\decoding.py", line 127, in __call__
    return self.decode(stream)
  File "C:\global_python_env\lib\site-packages\eth_abi\decoding.py", line 144, in decode
    stream.push_frame(start_pos)
  File "C:\global_python_env\lib\site-packages\eth_abi\decoding.py", line 95, in push_frame
    self.seek_in_frame(0)
  File "C:\global_python_env\lib\site-packages\eth_abi\decoding.py", line 84, in seek_in_frame
    self.seek(self._total_offset + pos, *args, **kwargs)
OverflowError: Python int too large to convert to C ssize_t
```

**Comment by joseddg92** [comment]
Reproducible trying to decode this tx: https://bscscan.com/tx/0xc3bea1a0ae512cd3e0bf3afc0c3aee49dbd03b4ecde05d3e465a3b18fa0bf299

It may happen only with failed txs... Here is quick fix for decode_function in order to avoid raising ugly system Overflow exception to the user:

  ```
  try:
        values = decode_abi(types, args)
    except OverflowError:
        raise InputDataError("decoding failed: OverflowError (did the tx being parsed fail?)")
```

**Comment by kigawas** [comment]
It seems that failed transaction and overflow error share the same cause: overflowed numbers in input data. Need some investigations on the exceptions raised by eth_abi 🤔
